stages:
  - deploy

variables:
  DOCKER_TLS_CERTDIR: '/certs'

deploy:
  stage: deploy
  image: 'docker:latest'
  services:
    - docker:dind
  tags:
    - cicd
  only:
    - tags
  before_script:
    - echo "$DO_ACCESS_TOKEN" | docker login registry.digitalocean.com --username $DO_ACCESS_TOKEN --password-stdin
  script:
    - echo "NEXT_PUBLIC_API_URL=$BACKEND_API" > .env.local
    - docker build -t registry.digitalocean.com/ocw-container/ocw-frontend:latest -t registry.digitalocean.com/ocw-container/ocw-frontend:$CI_COMMIT_TAG .
    - docker push registry.digitalocean.com/ocw-container/ocw-frontend:$CI_COMMIT_TAG
    - docker push registry.digitalocean.com/ocw-container/ocw-frontend:latest
